theme: jekyll-theme-hacker

title: The Most Epic Statistical Significance Project Ever :D
description: Le projet de statistiques de Kaitlin et Rowan

github:
  simulation: https://frostforth.github.io/stats/simulation
